---
- name: Copy Files Playbook
  hosts: servers
  become: yes  # If you need sudo privileges to copy to certain directories

  tasks:
    - name: Copy files to remote server
      copy:
        src: /var/lib/jenkins/workspace/third-pipeline  # Specify the path of the local file
        dest: . # Specify the destination path on the remote server
