---
- name: Deploy Docker Containers
  hosts: all
  become: yes

  tasks:
    - name: Clone Git Repository
      git:
        repo: https://github.com/Naresh100893/amazon-image.git
        dest: /home/ubuntu/amz-image

  
