---
- name: Deploy Docker Containers
  hosts: servers
  become: yes

  tasks:
    - name: Clone Git Repository
      git:
        repo: https://github.com/Naresh100893/ansi-jenk.git
        dest: /var/lib/jenkins/workspace/third-pipeline

     
  
