pipeline {
	agent any
	
	stages{
		stage('code') {
			steps {
				git branch: 'main', url: 'https://github.com/Naresh100893/ansi-jenk.git'
			}
		}
		
		stage('ansible-dir') {
			steps {
				ansiblePlaybook checkMode: true, credentialsId: 'private-key', installation: 'ansible', inventory: 'dev.inv', playbook: 'docker.yaml', vaultTmpPath: ''
			}
		}
	}
}
